import assert from 'node:assert/strict';
import {reportMetrics,prepareReport,validateReport,automaticPallets,reportDowntimes,consumptionPreview} from '../src/production/model.mjs';
const events=[{type:'break',minutes:15},{type:'lunch',minutes:30},{type:'maintenance',minutes:20},{type:'breakdown',minutes:10,note:'Fault'}];
const bom={inventory_bom_lines:[{ingredient_id:'raw',quantity_per_unit:1,waste_rate:0}],inventory_bom_packaging_lines:[{ingredient_id:'pallet',packaging_type:'expendable',basis:'pallet',quantity:1,waste_rate:0}]};
const profile={pieces_per_box:10,boxes_per_pallet:4};
const r={start_time:'08:00',end_time:'16:00',ends_next_day:false,people:3,item_id:'fg',machine_quantity:90,scrap_quantity:0,rework_quantity:0,full_boxes:9,packaging_type:'expendable',report_mode:'production',downtime_events:events};
const m=reportMetrics(r,profile);
assert.equal(m.elapsed,480);assert.equal(m.totalDowntime,75);assert.equal(m.machine,405);assert.equal(m.laborHours,21.75);
const p=prepareReport(r,bom,profile);assert.equal(p.pallets,3);assert.equal(p.break_minutes,45);assert.equal(p.downtime_minutes,30);
assert.equal(validateReport(p,{station:{active:true},bom,profile}),null);
assert.equal(automaticPallets(r,bom,{...profile,boxes_per_pallet:null}),null);
assert.equal(validateReport(r,{station:{active:true},bom,profile:{...profile,boxes_per_pallet:null}}),'pr_pallet_capacity');
assert.equal(automaticPallets(r,{inventory_bom_packaging_lines:[]},profile),0);
assert.equal(consumptionPreview(r,bom,[{id:'raw',category:'RAW'}],profile).find(x=>x.ingredient_id==='pallet').quantity,3);
assert.equal(reportMetrics({...r,start_time:'23:30',end_time:'00:30',ends_next_day:true,downtime_events:[]}).machine,60);
assert.equal(reportMetrics({...r,downtime_events:[{type:'maintenance',minutes:0.1},{type:'maintenance',minutes:0.2}]}).idle,0);
assert.equal(validateReport({...r,downtime_events:[{type:'oops',minutes:10}]},{station:{active:true},bom,profile}),'pr_downtime_invalid');
assert.equal(validateReport({...r,downtime_events:[{type:'break',minutes:''}]},{station:{active:true},bom,profile}),'pr_downtime_invalid');
assert.equal(reportDowntimes({downtime_minutes:15,downtime_reason:'Old reason'})[0].type,'legacy');
assert.equal(reportDowntimes({downtime_minutes:15},{forEdit:true})[0].type,'');
console.log('PASS: automatic time, downtime types, overnight shifts, rounding, pallet capacity and consumption, legacy reports.');
