import assert from 'node:assert/strict';
import {localStart,localDate,dayRange,liveKpis} from '../src/production/live.mjs';
assert.equal(localStart('2026-02-30','08:00'),null);
assert.equal(localStart('2026-10-08','25:00'),null);
assert.equal(localStart('2026-10-08','8:00'),null);
assert.equal(new Date(localStart('2026-10-08','08:00')).getHours(),8);
assert.equal(localDate(new Date(2026,9,8,23,30)),'2026-10-08');
assert.equal(dayRange('2026-02-30'),null);
const range=dayRange('2026-10-08');assert.equal(new Date(range.p_from).getHours(),0);assert.equal(localDate(range.p_to),'2026-10-09');
const run={started_at:'2026-10-08T08:00:00Z',latest_at:'2026-10-08T10:00:00Z',latest_quantity:150,expected_quantity:200,attainment:75,critical_percent:75,warning_percent:90};
assert.equal(liveKpis(run).performance,'warning');assert.equal(liveKpis({...run,attainment:74.9}).performance,'critical');assert.equal(liveKpis({...run,attainment:90}).performance,'on_track');
assert.equal(liveKpis(run).gap,50);assert.equal(liveKpis(run).rate,75);
assert.equal(liveKpis({...run,latest_quantity:210}).gap,0);
const historical=liveKpis({...run,period_quantity:100,period_at:'2026-10-08T09:00:00Z'});assert.equal(historical.quantity,100);assert.equal(historical.rate,100);
const empty=liveKpis({...run,period_quantity:null,period_at:null});assert.equal(empty.quantity,0);assert.equal(empty.performance,'pending');
console.log('PASS: local date ranges, invalid dates/times, percentage colors, historical quantities and no future-data leakage');

import {dailyProducts,selectProducts,switchProduct,openCapture,sharedTimeRows,selectLiveProducts} from '../src/production/multi.mjs';
let nextId=0;const newId=()=>String(++nextId);
let capture=selectProducts({id:'initial',station_code:'M1',people:2,start_time:'08:00',end_time:'16:00',machine_quantity:'0',scrap_quantity:'0',rework_quantity:'0',full_boxes:'0',pallets:'0'},['a','b'],newId);
capture={...capture,machine_quantity:'7',full_boxes:'1',packaging_type:'carton-7'};
capture=switchProduct(capture,'b');capture={...capture,machine_quantity:'11',full_boxes:'11',packaging_type:'carton-1'};
capture=switchProduct(capture,'a');
assert.equal(capture.machine_quantity,'7');assert.equal(capture.packaging_type,'carton-7');
const products=dailyProducts({...capture,people:3});
assert.deepEqual(products.map(p=>[p.item_id,p.machine_quantity,p.full_boxes,p.people]),[['a','7','1',3],['b','11','11',3]]);
assert.notEqual(products[0].id,products[1].id);
const reduced=selectProducts(capture,['b'],newId);assert.equal(reduced.machine_quantity,'11');
const reopened=openCapture({...products[0],capture_group_id:'group',status:'draft'},products.map(p=>({...p,capture_group_id:'group',status:'draft'})));
assert.equal(dailyProducts(reopened).length,2);
assert.equal(sharedTimeRows([{id:'a',capture_group_id:'group'},{id:'b',capture_group_id:'group'},{id:'c',capture_group_id:'other'},{id:'legacy'}]).length,3);
let live=selectLiveProducts({},['a','b'],newId);
live.products[0].quantity='7';live.products[1].quantity='11';
live=selectLiveProducts(live,['b','a'],newId);
assert.deepEqual(live.products.map(p=>[p.item_id,p.quantity]),[['b','11'],['a','7']]);
console.log('PASS: multi-product quantities, packing, switching, selection changes, reopened capture, independent checkpoint IDs and shared time deduplication');

const deselected=selectProducts(capture,[],newId);assert.deepEqual(dailyProducts(deselected),[]);
const oneLeft=selectLiveProducts(live,['b'],newId);assert.equal(oneLeft.quantity,'11');assert.equal(oneLeft.products.length,1);
assert.equal(selectLiveProducts(oneLeft,[],newId).item_id,'');
console.log('PASS: deselecting one product preserves the others and their quantities; all products can be removed');
